name: Build

on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          gradle-version: 8.8
      - uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: mod_version
      - name: mc-publish-fabric
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          version: ${{ steps.version.outputs.value }}
          curseforge-id: 1239946
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          files-primary: fabric/build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          loaders: fabric
          game-versions: 1.20.1
          name: ""
          changelog-file: changelog.*
      - name: mc-publish-forge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          version: ${{ steps.version.outputs.value }}
          curseforge-id: 1239946
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          files-primary: forge/build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          loaders: forge
          game-versions: 1.20.1
          name: ""
          changelog-file: changelog.*
      - name: Nuke Changelog dot txt
        uses: DamianReeves/write-file-action@master
        with:
          path: changelog-1.21.txt
          write-mode: overwrite
          contents: |
            CHANGELOG:
      - name: Increment version variable
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.2.3
        with:
          current-version: ${{ steps.version.outputs.value }}
          version-fragment: 'hotfix'
      - name: Replace single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'gradle.properties'
          search-text: ${{ steps.version.outputs.value }}
          replacement-text: ${{ steps.bump_version.outputs.next-version }}
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GIT_TOKEN}}
          branch: ${{ github.ref }}
          force: true
